### ISSUE TITLE
Create a table of Colab links to all the notebooks

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/Environmental-Enforcement-Watch#15]
Probably separate from the repo directory because that's more of a guide for contributors

**Comment by ericnost** [comment]
Can someone confirm that the Colab links will also point to the latest version? That way we don't have to constantly create new Colab links. For instance, for the CWA Enforcements notebook, we could use this link: https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Clean-Water-Act/blob/master/echo-cwa-enforcements.ipynb which points to the master branch. Anytime master branch is updated, I believe (but am seeking confirmation) that the Colab notebook should be updated.

**Comment by Frijol** [comment]
Yes, can confirm!
