### ISSUE TITLE
Template for Notebooks

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/Environmental-Enforcement-Watch#24]
Shall we make a  template for standard layout of Notebooks? Based on current conversation, it would include:

* Title
* EEW logo and linkback to site
* Instructions on use of notebook
* Licensing block

(Anything else?)

┆Issue is synchronized with this [Trello card](https://trello.com/c/QJqjUM7z)

**Comment by ericnost** [comment]
Related to #18
