### ISSUE TITLE
EJ-focused notebooks

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/Environmental-Enforcement-Watch#29]
Thinking about what an environmental justice-focused notebook might look like.

* Meaningful scale: needs to cross multiple demographies. Congressional district? State?
* Visual output: most likely mapping. Idea is to show intersection of demographics with polluting facilities
* Need additional demographic dataset. Census data?

Potential outputs:
* Heatmap/color map of demographics (race, economics?) overlaid with bubbles that show pollution amts of facilities
* Comparison of demographics between best & worst areas in region for pollution (bar chart?)

**Comment by ericnost** [comment]
<img width="881" alt="Screen Shot 2020-06-11 at 7 16 07 PM" src="https://user-images.githubusercontent.com/6888951/84448208-0b7aa100-ac18-11ea-8dbd-fc99848bfec0.png">
<img width="228" alt="Screen Shot 2020-06-11 at 7 16 13 PM" src="https://user-images.githubusercontent.com/6888951/84448212-0d446480-ac18-11ea-9144-257df39ad814.png">

**Comment by ericnost** [comment]
<img width="140" alt="Screen Shot 2020-06-11 at 7 17 14 PM" src="https://user-images.githubusercontent.com/6888951/84448270-2cdb8d00-ac18-11ea-8854-8f61c2780569.png">
The bigger the circle, the more hazardous waste the facility imported from CAN/MEX.

**Comment by ericnost** [comment]
Also want to acknowledge here, as EDGI has elsewhere and many scholars too, that correlating neighbourhood demographics and pollution is a very limited, if necessary first step, approach to what environmental injustice is and how it happens.

**Comment by ericnost** [comment]
Also see some of the information we can pull from EJScreen through ECHO (cc: @crgreenleaf) https://echo.epa.gov/tools/web-services/detailed-facility-report#/Detailed%20Facility%20Report/get_dfr_rest_services_get_ejscreen_indexes
